### ISSUE TITLE
it seens not work for spring boot 1.5.3release with tomcat

### ISSUE THREAD

**Issue by FlowerWrong** [corentin59/spring-boot-graceful-shutdown#2]
`curl -i http://127.0.0.1:8000/gracefulshutdown` return 404.

**Comment by corentin59** [comment]
Hi,

Actuator is enabled ?

**Comment by FlowerWrong** [comment]
Yes it is. i can use `curl -i -X POST http://127.0.0.1:8000/shutdown` to shutdown the server.
